import 'package:expandable/expandable.dart';
import 'package:flutter/material.dart';
import 'package:smart_karabakh/constants/const_styles.dart';

class InfoPage extends StatefulWidget {
  const InfoPage({Key? key}) : super(key: key);

  @override
  State<InfoPage> createState() => _InfoPageState();
}

class _InfoPageState extends State<InfoPage> {
  List<InfoModel> data = [
    InfoModel("assets/agdam.png", "Ağdam",
        '''Ağdam rayonu Ağcabədi, Tərtər, Bərdə, Kəlbəcər Əsgəran və Xocavənd həmçinin, Füzuli rayonları ilə həmsərhəddir. Ərazisi 1,15 min kv km, əhalinin sayı isə 204,0 min nəfərdir (01.01.2020). Rayon kimi yaranma tarixi 08.08.1930-cu il. Ağdam rayonunda 1 şəhər, 2 qəsəbə (Quzanlı, Açarlı) 123 kənd vardı. Kəndləri bunlardır – Eyvazlı, Bağbanlar, İsmayılbəyli, Muğanlı, Pirzadlı, Saybalı, Baş Güneypəyə, Boyəhmədli, Qızıl Kəngərli, Mollalar, Salahlı Kəngərli, Sofulu, Çəmənli, Sarıcalı, Şükürağalı, Əfətli, Hacıməmmədli, Hacıturalı, Həsənxanlı, İsalar, Küdürlü, Qəhrəmanbəyli, Məmmədbağırlı, Əhmədağalı, Çıraxlı, Kolqışlaq, Mirəşelli, Əlimədətli, Cinli, Əliağalı, Xaçındərbətli, Kürdlər, Qalayçılar, Mollalar, Göytəpə, Abdınlı, Cavahirli, Kosalar, Gülablı, Abdal, Əhmədavar, Xındırıstan, Baharlı, Bəybabalar, Birinci Yüzbaşılı, Dadaşlı, İkinci Yüzbaşılı, Kəlbəhüseynli, Paşabəyli, Sarıçoban, İmamqulubəyli, Çullu, Kəngərli, Qaraqaşlı, Şirvanlı, Qaradağlı, Evoğlu, Rzalar, Qasımlı, Qaradağlı, Qurdlar, Poladlı, Şelli, Baş Qərvənd, Ayaq Qərvənd, Qazançı, Şıxlar, Qiyaslı, Ətyeməzli, Keştazlı, Maqsudlu, Çullu, Eyvazxanbəyli, Şahbulaq, Salahsəmədlər, Şişpapaqlar, Talışlar, Təpəməhlə, Tərnöyüt, Tükəzbanlı, Məlikli, Orta Qərvənd, Güllücə, İlxıçılar, Suma, Tağıbəyli, Xatınbəyli, Xıdırlı, Çuxurməhlə, Mərzili, Nəmirli, Şoltanlı, Şuraabad, Təzəkənd, Umudlu, Novruzlu, Orta Güneypəyə, Papravənd, Ballar, Sarıcalı, Qarazeynallı, Qullar, Seyidli, Bozpapaqlar, Sarıhacılı, Sırxavənd, Ballıqaya, Bəşirlər, Qaraşlar, Şıxbabalı, Muğanlı, Üçoğlan, Alıbəyli, Baharlı, Qarapirimli, Böyükbəyli, Kiçikli, Orta Qışlaq, Yeni Qaralar, Mahrızlı, Yusifcanlı, Zəngişalı, Yusifli.
Rayonun mərkəzi olan Ağdam Bakıdan 362 km məsafədə, Qarqar çayının sahilindən 3 km aralı, Qarabağ düzünün cənub-qərbindədir.
Ağdam ağır, yeyinti və yüngül sənayeyə, inkişaf etmiş kənd təsərrüfatına malik rayon idi.
Ağdamda dəzgah avadanlıqları, aerokosmik və rabitə cihazları, metis-furnitur, traktor və avtomobil təmiri, asfalt, konserv, yağ-pendir, barama toxumu, pambıq, şərab və mexanikləşdirilmiş çörək zavodları, xalça fabriki, taxıl məhsulları, tikinti materialları və ət kombinatları, iki dəmiryol vağzalı və aeroport, avtomobillərə texniki xidmət stansiyaları, məişət xidməti kombinatı, elektrik şəbəkəsi, kənd təsərrüfatı, kənd təsərrüfatının mexanikləşdirilməsi və elektrikləşdirilməsi stansiyaları, Üzeyir Hacıbəyov adına musiqi texnikumu, Ə. Haqverdiyev adına Ağdam Dövlət Dram Teatrı fəaliyyət göstərirdi. Həmçinin, 38 kolxoz və sovxoz, 24 tikinti-quraşdırma idarəsi, 12 sənaye müəssisəsi, 74 məktəb, 105 səhiyyə müəssisəsi, 271 mədəniyyət evi, 67 idarə, 99 klub işğal altında qalmışdır.
Rayon ərazisinin 1700 hektarı meşəlik, 28 min hektar sahə isə kənd təsərrüfatına yararlı torpaqlardan ibarət idi. Kənd təsərrüfatının istiqaməti, əsasən, pambıqçılıq, üzümçülük və heyvandarlıqdı.
Mövcud dövlətini qədim Azərbaycan torpaqları üzərində qurmuş Ermənistan Dağlıq Qarabağı özünə birləşdirmək məqsədilə 1988-ci ilin fevral ayından başladığı müharibəyə Ağdam rayonu da cəlb olunmuş, hadisələrin ilk günlərindən ən böyük ağırlıq Ağdam rayonunun üzərinə düşmüşdür, 1988-ci ilin son aylarında Ermənistandan-öz dədə-baba yurd-yuvasından, daha sonra isə Dağlıq Qarabağdan doğma ocaqlarından qovulub çıxarılan on minlərlə azərbaycanlı məhz Ağdam rayonuna pənah gətirmişdi. 1992-ci ildə Dağlıq Qarabağı bütünlüklə işğal edən Ermənistan bununla kifayətlənməyərək, Dağlıq Qarabağın ətrafında yerləşən rayonlara da dişini qıcadı.
Ermənistanın separatçı hakimiyyəti bəzi xarici dövlətlərin yaxından köməyi, bilavasitə iştirakı ilə Şuşa, Laçın, Kəlbəcər rayonlarını işğal etdikdən sonra Ağdamı hədəf seçdi. Ermənilər bu rayonu da ələ keçirmək üçün irimiqyaslı hücum əməliyyatlarına başladılar. 1993-cü il iyun ayının 11-dən başlayaraq bu hücum, həmin ilin iyul ayının 23-də Ağdamın işğalı ilə başa çatdı. 1905-1907-ci illərdə, 1918-1920-ci illərdə düşmən ayağı dəyməyən Ağdam beş illik mübarizədən sonra işğal olundu.
1994-cü il may ayının 12-dək davam edən hərbi təcavüz nəticəsində isə ermənilər Ağdam rayonu ərazisinin 846,7 kvadrat kilometrini, yəni ümumi ərazisinin 77,4 faizini işğal etməyə nail oldular. İşğal edilmiş Ağdam şəhəri və rayonun 89 kəndi bəşər tarixində bənzəri olmayan bir vəhşiliklə darmadağın edilərək, yerlə-yeksan edildi. Ağdamın müdafiəsi uğrunda 5 ildən artıq gedən qanlı döyüşlərdə qismətinə 5897 şəhid, 3531 nəfər əlil, 1871 nəfər yetim uşaq düşdü. Minlərlə insan fiziki şikəstlik qazanmış, 126 min (1993) nəfərdən artıq ağdamlı öz doğma ev-eşiyindən didərgin düşmüşdü.
Ağdam rayonu 20 noyabr 2020 - ci ildə Ermənistan işğalından azad olunmuşdur. Qarabağ Azərbaycandır!
'''),
    InfoModel(
      "assets/xankendi.png",
      "Xankəndi",
      '''Xankəndi Qarqar çayının sahilində, Qarabağ silsiləsinin şərq ətəyində, Bakıdan 385 km aralıda yerləşir. İnzibati cəhətdən Xankəndi şəhər əhatə dairəsinə Xankəndi şəhəri və Kərkicahan qəsəbəsi daxildir. Dağlıq Qarabağ Muxtar Vilayətinin mərkəzi olmuşdur. Sahəsi 8,8 km²-dir. Əhalisinin sayi 55.9 min nəfərdir (01.01.2020) Xankəndi şəhəri erməni silahlı qüvvələri tərəfindən 28.12.1991-ci ildə işğal olunmuşdur.
Xankəndi şəhəri şimaldan Kəlbəcər, Tərtər, Ağdərə, Ağdam, cənubdan Şuşa, şərqdən Xocavənd, qərbdən Laçın, mərkəzdən isə Xocalı və Əsgəran rayonları ilə əhatə olunmuşdur.
Xankəndi digər Azərbaycan şəhərlərinin əksəriyyətindən nisbətən cavan olması ilə fərqlənir. Arxiv sənədlərinə görə şəhər XVIII əsrin axırlarında Qarabağ xanlarının istirahəti üçün yaşayış məskəni kimi salınmışdır. Xanların fəaliyyətinə maksimum şərait yaradılması üçün məskən xanlığın paytaxtı Pənahabadın (indiki Şuşanın) 10 kilometrliyində, nisbətən dağ ətəyində salınır. İlk illər yeni yaşayış məskənində ancaq xan ailəsi və onun yaxınları yaşadığından el arasında "Xanın kəndi" kimi tanınır. Qısa bir müddətdən sonra isə Xankəndi adını alır. Xankəndi Qarabağ xanlarının istirahət mərkəzi kimi salınsa da, XX əsrdə o, Azərbaycanın yeni sənaye və mədəniyyət mərkəzi kimi inkişaf etməyə başlayır. Bu zaman bu işə daima Azərbaycanın ümumi respublika resurslarından böyük dəstək verilir.
Xankəndində tikilmiş müəssisələr vilayətin sənaye məhsulunun yarısından çoxunu istehsal edirdi. Xankəndində bütün Cənubi Qafqazda tanınan ipək kombinatı, ayaqqabı, xalça, tikiş fabrikləri, süd kombinatı və şərab zavodu fəaliyyət göstərirdi. Elektrotexniki zavodun, mebel fabrikinin, tikinti materialları kombinatının məhsulları isə Azərbaycanın daxili bazarında özünə layiqli yer tutmuşdur.
Azərbaycan Mərkəzi İcraiyyə Komitəsi Sovetlərinin 07. 07. 1923-cü il tarixli Dekretinə əsasən Dağlıq Qarabağ Muxtar Vilayəti yaradılarkən, həmin Vilayətin mərkəzi Xankəndi şəhəri olmuşdur. 18. 09. 1923-cü ildə isə Qarabağ Vilayət Partiya Komitəsinin qərarı ilə Xankəndi şəhərinin adı dəyişdirilərək Stapanakert şəhəri adlandırılmışdır.
Azərbaycan SSR Ali Sovet Rəyasət Heyətinin 15. 05. 1978-ci il tarixli, 837-IX nömrəli Fərmanı ilə Stepanakert rayonunun mərkəzi Stepanakert şəhərindən Əsgəran fəhlə qəsəbəsinə keçirilmiş və Stepanakert rayonu Əsgəran rayonu adlandırılmışdır.
Azərbaycan SSR Ali Sovet Rəyasət Heyətinin 21. 04. 1990-cı il tarixli, 1783-XI nömrəli Fərmanına əsasən Stepanakert şəhərinin Kərkicahan yaşayış massivi şəhər tipli qəsəbələr kateqoriyasına aid edilmiş və Stepanakert Şəhər Sovetinin tərkibində Kərkicahan Qəsəbə Soveti yaradılmışdır.
“Azərbaycan Respublikasının Dağlıq Qarabağ Muxtar Vilayətini ləğv etmək haqqında” 26 noyabr 1991-ci il tarixli, 279-XII nömrəli Azərbaycan Respublikasının Qanununa əsasən isə şəhərin tarixi adı qaytarılaraq Stepanakert şəhəri Xankəndi şəhəri adlandırılmışdır.
İkinci Qarabağ müharibəsi (27 sentyabr - 09 noyabr 2020) nəticəsində Xankəndi şəhəri üzərində Azərbaycanın suverenliyi bərqərar olmuş, Azərbaycan Respublikasının ərazi bütövlüyü bərpa olunmuşdur. Qarabağ Azərbaycandır!
''',
    ),
    InfoModel(
      "assets/susa.png",
      "Şuşa",
      '''Ümumi məlumat
Şuşa 08.08.1930-cu ildə inzibati rayon statusu almışdır. Mərkəzi Şuşa şəhəridir. Ərazisi 0. 29 min km2, əhalisinin sayı 34,7 min (01.01.2020) nəfərdir. 1992-ci il may ayının 8-də erməni birləşmələri tərəfindən işğal edilmişdir.
İşğaldan qabaq ərazidə 1 şəhər, 1 qəsəbə (Turşsu), 37 kənd olub. Kəndləri bunlardır - Daşaltı, Göytala, Xanalı, Həsənabad, İmamqullar, Xəlfəli, Armudlu, Dükanlar, Qarabulaq, Laçınlar, Mirzələr, Şuşulu, Zamanpəyəsi, Böyük Qaladərəsi, Kiçik Qaladərəsi, Qaybalı, Xudaverdilər, Nağılar, Yuxarı Quşçular, Aşağı Quşçular, Malıbəyli, Sarıbaba, Onverst, Səfixanlar, Allahqullar, Həsənqullar, Xanlıqpəyə, Şırlan, Ağbulaq, Cəmillər, Çaykənd, İmanlar, Məmişlər, Paşalar, Turabxan, Zarıslı, Nəbilər.
Şuşada Dövlət Dram Tеatrı, Şuşa televiziyası, Dövlət Qarabağ tariхi və Şuşa şəhərinin tariхi muzеyləri, Üzеyir Hacıbəyоvun, Bülbülün, Mir Möhsün Nəvvabın хatirə muzеyləri, Azərbaycan Хalçası Dövlət Muzеyinin filialı, Dövlət Rəsm Qalеrеyası, dörd texnikum, iki inistitut filialı, texniki peşə məktəbi, 25 orta məкtəb, оrta və оrta iхtisas musiqi məкtəbləri, 7 uşaq bağçası, 8 mədəniyyət evi, 17 klub, 31 кitabхana, 40 tibb müəssisəsi, 2 sanatoriya, Uşaq sanatoriyası, Uşaq sağlamlıq məktəbi, 70 yerlik turist bazası, mehmanxana, 5 mədəniyyət və istirahət parkı, 4 kinoteatr, ictimai iaşə obyektləri fəaliyyət göstərirdi.
Rayonun iqtisadiyyatında heyvandarlıq əsas yer tuturdu. Kənd təsərrüfatına yararlı torpaqlar 20,9 min hektardı (1986). Bunun 3,8 min hektarı şum yeri, 0,1 min hektarı çoxillik bitkilər, 0,3 min hektarı biçənəklər, 16,7 min hektarı otlaqlardır. Suvarılan torpaqlar 0,1 min hektar idi. 3,4 min ha əkin sahəsinin 41% -ə dənli və dənli – paxlalı bitkilər (buğda, arpa, qarğıdalı), 6 % -ində tərəvəz-bostan bitkiləri və kartof, 53%-ində yem bitkiləri əkilir. Meyvəçiliklə də məşğul olunurdu. 5,2 min qara- mal, 15,2 min davar vardı (1986). Quşçuluqla da məşğul olunurdu.
Şərq musiqi alətləri fabrikiki, istehsalat kombinatı, çörəkbişirmə müəssisəsi, məişət xidməti kombinatı, rayon İstehlak cəmiyyəti, Kurort ticarəti idarəsi, Bakı "Radioqurma" istehsalat birliyinin 1 №-li istehsalatı, Qarabağ ipək kombinatının 3 №-li toxuculuq sexi, elektrik şəbəkəsi, rayon Maddi-texniki təchizat bazası, Abidələri bərpa idarəsi, Şuşa Tikinti birliyi, Təsərrüfatlar arası tikinti idarəsi, Təmir tikinti idarəsi, Təsərrüfatlar arası təmir tikinti müəssisəsi, Yol istismar idarəsi və s. var idi. Kurort təsərrüfatı inkişaf etmişdi.
Yevlax-Naxçıvan avtomobil yolu və qaz kəməri Şuşa. rayonundan keçirdi. Şuşa rayonu ilə Bakı arasında olan məsafə 373 kilometrdir.
Şuşada 17 məhəllə vardı: Qurdlar, Seyidli, Culfalar, Quyuluq, Çuxur, Dördlər Qurdu, Hacı Yusifli, Dörd Çinar, Çöl Qala, Mərdinli, Saatlı, Köçərli, Mamayı, Xoca Mərcanlı, Dəmirçi, Hamam Qabağı və Təzə məhəllə. Hər məhəllədə hamam, məcid, bulaq vardı. Vaxtilə müstəqil Azərbaycanın memarı olan Heydər Əliyevin abidələr şəhəri adlandırdığı Şuşada 350 hektarlıq qoruq zonasında 300 tarixi abidə, 550 qədim yaşayış binası, 870 m uzunluğunda bərpa olunmuş qala divarları vardı. Tarixi abidələrdən 23-ü respublika və dünya miqyaslı abidələrə aid idi. Şuşada milli abidələrin çoxluğu, onların rəngarənglik baxımından fərqlənməsi, haqlı olaraq, şəhərin mədəniyyətimizin ən zəngin beşiyi adlandırılmasına səbəb olmuşdur. Bu abidələrin çoxu XVIII-XIX əsirlərə aiddir. Şuşada hər bir ev, küçə, möhtəşəm qala divarları, məscidlər, qəd-qamətli minarələr, əzəmətli qəsrlərin qalıqları keçmişimizdən xəbər verir.
Ərazisi dağlıqdır (Qarabağ dağ silsiləsi). Ən yüksək zirvəsi Böyük Kirs dağıdır (2725 m. ). Keçəldağ aşırımı Şuşa rayonundadır. Əsasən, Yura və Tabaşir çöküntüləri yayılmışdır. Müxtəlif növ tikinti materialı yataqları və mineral su bulaqları (Turşsu, Şırlan) var. Rayon ərazisindən Qarqar çayı axır. Torpaqları əsasən, qəhvəyi dağ-meşə, çimli dağ-çəməndir. Yüksək dağlıq sahədə subalp və alp çəmənlikləri ilə örtülüdür.
Şuşa üzlük daşı yatağı; ehtiyatları 397 min m3 olan kərpic-kirəmit istehsalına yararlı Keçəldağ (Lesoqor) gil yatağı; istismar ehtiyatları 389 min m3/gün olan Şuşa yeraltı şirin su yatağı; 342 min m3/gün və 70 min m3/gün olan Şırlan və Turşsu mineral su yataqları var.
Daşaltı Dövlət Təbiət yasaqlığı. Şuşa və Əsgəran ərazisində nadir təbiət komplekslərini qorumaq üçün 1988-ci ildə təşkil edilən bu yasaqlıq 450 hektar ərazini əhatə edirdi.
Şuşa havasının tərkibi, təmizliyi, saflığı və müalicə əhəmiyyəti baxımından kurort şəhəridir. Bu baxımdan, nəinki, Azərbaycanda, onun hüdudlarından kənarda da Şuşa öz səfalı yerləri, istirahət guşələrinə görə məşhur idi.
Şuşa dağlarında xüsusi gözəlliyi olan bir gül var. Bu gül dünyanın heç bir yerində bitmir. Təbiətin Şuşa dağlarında yaratdığı bu möcüzə xarı bülbül adlanır. Gülün üst tərəfi elə formadadır ki, sanki gülün üstünə bülbül qonub və oradaca donub qalıb.
Turşsu yaylaqları, Səkili bulağı, İsa bulağı. Şəmilin bulağı, əfsanəvi “Cıdır düzü” yerli camaatın və oraya təşrif buyuran qonaqların ən sevimli yeri idi.
Turşsu istirahət və müalicə zonası kimi tanınırdı. Şuşadan 40 km. aralıda – Laçın yolunun üstündə yerləşir. Sol tərəfdən isə Daşaltı çayı axır. Turşsu şəfalı və müalicəvi vannaları ilə məşhur idi.
Şuşanın gəzməli görməli yerlərindən biri də Yuxarı Daşaltı idi. Xalq arasında bu istirahət yerinə Şəmilin bağı da deyirdilər. Bu yerin özünəməxsus xüsusiyyəti ondan ibarətdir ki, istirahət guşəsi Daşaltı çayının üstündə, “Ağzıyastı kaha” yerləşən Üçmıx dağının düz altında, çeşmə ətrafında yerləşir.
Şuşaya təşrif buyuran turistlərin ən sevimli yerlərindən biri də əvəzsiz və əsrarəngiz təbiətə malik əfsanəvi “Cıdır düzü” idi. “Cıdır düzü”nün qərb tərəfi bir-birinin arxasında yerləşən üç hündürlükdən ibarətdir. Bu təpələrə “Üçmıx” adı verilib.
Sanatoriya və istirahət evlərində dincələn turistlər daim həmin yerlərə gəzintilərə çıxır, təbiətin Şuşaya bəxş etdiyi gözəllik qarşısında öz təəccüblərini gizlədə bilmirdilər. Əhalinin və turistlərin əsas istirahət yerlərindən biri olan “Cıdır düzü”ndə hər il may ayında “Xarı-bülbül” mahnı festivalları keçirilirdi.
Şuşa 1992-il mayın 8-də еrməni və rus işğalçıları tərəfindən işğal еdildi. Şuşanın işğal günü bütün Azərbaycan хalqının mənəviyyatına vurulmuş ağır bir zərbə, bizim hamımız üçün ağır bir dərddir.
Şuşanın işğalı zamanı 200 nəfər şəhid olmuş, 150 nəfər əlil olmuş, 552 körpə yetim qalmış, 22 minə yaxın insan qaçqın düşmüşdür,
Şuşa işğal edilərkən, əldə olunan məlumatlara görə, bu quldurlar tarixi abidələrimizi vəhşicəsinə dağıtmış və yerlə yeksan etmişdir.
Erməni silahlı qüvvələri Şuşanı işğal edərkən 15 ədəd etnoqrafik nümunə, 5 ədəd mis məmulatı, 2 ədəd gümüş xəncər, 1 ədəd daş qazan, 20 ədəd daş-qaşla bəzədilmiş müxtəlif əşya və digər qiymətli əşyaları Şuşa şəhər muzeyindən; 5 ədəd qiymətli qədim xalçanı, 4 ədəd kilimi, 5 ədəd xurcunu, 1 ədəd qiymətli nadir çırağı, Üzeyir Hacıbəyovun portretini və çoxsaylı digər qiymətli tarixi əşyaları Qarabağ tarix muzeyindən, Mir Möhsün Nəvvabın və Bülbülün ev muzeyindən olduqca çoxlu qiymətli və nadir əşyaları qarət etmişlər. Şuşa muzеylərinin qiymətli sərvətləri - rəsm və hеyкəltəraşlıq əsərlərini, хalça və хalça məmulatlarını, хalq tətbiqi sənət nümunələrini, arхеоlоji tapıntıları, çох gərəкli sənədləri, Azərbaycanın görкəmli şəхsiyyətlərinin хatirə əşyalarını, digər qiymətli matеrialları Еrmənistana aparmışlar. İndi həmin əşyalar хarici auкsiоnlarda satılır, yaхud müхtəlif sərgi və muzеylərdə dünya ictimaiyyətinə еrməni mədəniyyət nümunəsi кimi təqdim оlunur.
Bəli, ХХ əsrin sonunda Şuşa tariхdə görünməmiş faciəli hadisələrlə üzləşdi, işğal оlundu. Övladları yеrindən-yurdundan didərgin düşdü, şəhidlər vеrdi, ancaq əsrlər bоyu оlduğu кimi sınmadı, əyilmədi və Şuşa indi də yaşayır. Onun əhalisi rеspubliкanın 59 rayоnunda 700 yaşayış məntəqəsində məsкunlaşmışdır.
Qеyd еtməк lazımdır кi, Şuşa indi düşmən əlində оlsa da, əsrin əvvəllərində Şuşada fəaliyyət göstərən bir çох mədəniyyət və təhsil оcaqları işğaldan sоnra öz işlərini Baкı şəhərində və rеspubliкanın başqa bölgələrində davam еtdirirlər.
Şuşa şəhəri  8 noyabr 2020- ci ildə Ermənistan işğalından azad olunmuşdur. Qarabağ Azərbaycandır!
''',
    ),
    InfoModel(
      "assets/kelbecer.png",
      "Kəlbəcər",
      '''Ümumi məlumat
Kəlbəcər rayonu Qərbdə Ermənistan respublikası, şimalda Daşkəsən, Xanlar (Göy-Göl), Goranboy, şimali-şərqdə Tərtər, şərqdə Ağdam, Xocalı, cənubda Laçın rayonları ilə həmsərhəddir. Sahəsi 3054 km2 olan rayonda bir şəhər, bir şəhər tipli qəsəbə (İstisu), 145 kənd vardı. Ağdərə rayonunun 20-yə qədər kəndi də Kəlbəcər inzibati bölgüsünə daxildir. Mərkəzi Kəlbəcər şəhəridir. 8 avqust 1930-cu ildə inzibati rayon statusu almışdır. Kəndləri bunlardır – Abdullauşağı, Ağyataq, Fətallar, Moz, Mozqaraçanlı, Ağcakənd, Oruclu, Təzəkənd, Zağalar, Ağdaban, Bağırlı, Çayqovuşan, Almalıq, Böyükdüz, Laçın, Aşağı Ayrım, Boyaqlı, Yuxarı Ayrım, Bağlıpəyə, Vəng, Başlıbel, Alırzalar, Çovdar, Xallanlı, Şahkərəm, Comərd, Qaragüney, Nəcəfalı, Pirilər, Çaykənd, Kəndyeri, Qasımlar, Mişni, Rəhimli, Çəpli, Zülfüqarlı, Çərəkdar, Çıldıran, Türkeşəvənd, Qalaboyun, Qaraxançallı, Yanşaqbinə, Alolar, Armudlu, Bəzirxana, Hacımalılar, İlyaslar, Dəvədaşı, Mehmana, Çıraq, Məmmədsəfi, Tövlədərə, Dalqılınclı, Barmaqbinə, Dərəqışlaq, Otaqlı, Otqışlaq, Daşbulaq, Alçalı, Allıkənd, Boyur, Dəmirçidam, Qanlıkənd, Bazarkənd, Dovşanlı, Hayad, Əsrik, Çobangərəhməz, Çorman, Tirkeşəvənd, Günəşli, Alçalı, Nəbilər, Hacıkənd, Başkənd, Heyvalı, Yayıcı, Həsənriz, İstibulaq, Ağdaş, Göydərə, Keşdək, Kərəmli, Kolatağ, Damğalı, Qamışlı, Bağırsaq, Keçiliqaya, Zərqulu, Vəngli, Zallar, Həsənlər, Zəylik, Kaha, Hopurlu, Qazıxanlı, Orta Qaraçanlı, Aşağı Qaraçanlı, Baş Qaraçanlı, Xoləzəy, İmanbinəsi, Tatlar, Qılınclı, Alçalı, Quzeyçikin, Qızılqaya, Yuxarı Oratağ, Çopurlu, Qozlu, Qozlukörpü, Lev, Mərcimək, Ağqaya, Birinci Milli, İkinci Milli, Üçüncü Milli, Mollabayramlı, Nadirxanlı, Narınclar, Sarıdaş, Güneypəyə, Seyidlər, Cəmilli, Susuzluq, Qasımbinəsi, Şaplar, Məmməduşağı, Aşağı Şurtan, Orta Şurtan, Soyuqbulaq, Yuxarı Şurtan, Taxtabaşı, Yenikənd, Təkəqaya, Babaşlar, Bozlu, Çormanlı, Qaragüney, Yanşaq, Yellicə, Təkdam, Zar, Şeyinli, Zivel, Şahmansurlu.
Kəlbəcər rayonunun əhalisinin sayı 94,1 min (01.01.2020) nəfərdi. Kəlbəcər əhalisinin 98 faizini Azərbaycanlılar, 2 faizini isə, ruslar, İrandan gəlmə kürdlər və başqa millətlər təşkil edir.
"Kəlbəcər" toponiminin mənşəyi qədim türk dilində (oykonimin ilkin forması Kevliçer kimi qəbul edilib) "çay üstündə qala" deməkdir. Kevli "çayın üstü", çer/car "qala" mənasını verir. Yaşayış məntəqəsinin yerləşdiyi qayada Tərtərçay çayı boyunca cərgə ilə düzülmüş qədim süni mağaralar mövcuddur. Buna görə də mütəxəssislər toponimi kevil/kəvl və qədim türk dillərindəki cər (qaya, yarğan) komponentləri ilə əlaqələndirirlər.
Səthi dağlıqdır (Murovdağ, Şahdağ, Şərqi Sevan (Göyçə), Vardenis, Mıxtökən, Qarabağ silsiləsinin və Qarabağ yaylasının bir hissəsi). Ən yüksək zirvəsi Camış dağı (3724) və Dəlidağdır (3616). Ərazidə Yura, Tabaşir, Paleogen, Neogen və Antropogen çökmə, vulkanogen-çökmə və vulkanik süxurları yayılmışdır. Ən böyük çayı Tərtər və onun qolları (Lev çayı, Tutqunçay və sair) Bazarçayın da mənbəyi Kəlbəcər rayonu ərazisindədir. Rayonun mərkəzi və şimal hissəsində enliyarpaqlı meşələr, meşə-çöl bitkiləri, yüksək və qismən orta dağlarda alp və subalp çəmənlikləri geniş yer tutur. Meşələrinin ümumi sahəsi 32774 hektardır. Qaya keçisi, qonur ayı, çöl donuzu, daşlıq dələsi, ular, qartal və sair faunasını zənginləşdirir.
Kəlbəcər şəhəri Bakıdan təxminən 450 km qərbdə, Bərdə - İstisu (Kəlbəcər) avtomobil yolunun kənarında, Tərtər (çay) çayı sahilində, sıldırım qayalıqlar üzərində yerləşir.
Şəhərdə Respublika Dövlət Kənd Təsərrüfatı İstehsal-Texniki Təminat Komitəsinin rayon şöbəsi, məişət xidməti kombinatı, sanitariya-epidemioloji stansiya, 2 orta məktəb, musiqi məktəbi, mədəniyyət evi, 2 kütləvi kitabxana, mərkəzi rayon xəstəxanası, poliklinika, kinoteatr, doğum evi, iri ticarət, sənaye müəssisələri və s. vardı. Geniş dağ düzənliyi üzərində yerləşən Kəlbəcər şəhərini əhatə edən dağlar sanki öz ətəklərini şəhərin ayaqları altında yerə sərmişdir.
Azərbaycanın cənnət məkanı olan Kəlbəcər rayonunun ərazisini başdan-başa gülüstan adlandırmaq olar. Otuz mindən artıq bulağı olan, ilin bütün dövrlərində, hər çeşmə başında qonağı olan Kəlbəcər rayonu təbiətin muzeyidir. Rayon ərazisində 4 mindən artıq bitki növü bitir ki, bunlardan da 200-ü dərman bitkisidir. Zəngin meşələr diyarı olan Kəlbəcərdə yüzlərlə mineral bulaqlar mövcuddur. Min bir dərdin dərmanı olan İstisuyun şöhrəti, sinəsindən qarı-qırovu, zirvəsindən tufanı-çəni heç zaman əskik olmayan Murovun şıltaqlığı, hər il yamacları qonaq-qaralı olan Dəlidağın saysız-hesabsız gülü-çiçəyi aləmə bəllidir. Məhz bu səbəbdən də Qafqaz geologiyasının atası hesab edilən V. Avix Kəlbəcər haqqında demişdir ki: “Kim Tərtərçay dərəsi boyunca seyr etməmişdirsə, İsveçrənin gözəlliyinə yalnız o məftun ola bilər”.
Kəlbəcərə dünya şöhrəti qazandırmış Yuxarı İstisu, Aşağı İstisu, Keşdək, Qarasu, Mozçay, Bağırsaq, Qotursu kimi çox böyük müalicə - balneoloji təsirə malik mineral su yataqları da (ümumi istismar ehtiyatları 3093 m3/gün) işğal ərazisində yerləşir.
Təbiətin Kəlbəcərə bəxş etdiyi min bir nemətdən biri də bizi dünyaya tanıdan və loğman kimi neçə milyon insanı sağaldaraq həyata qaytaran dirlik suyu – İSTİSUDUR.
İstisu Kəlbəcərin qərb hissəsində silsilə dağ yamaclarındadır. Göyçə gölündən 300 verstlik yolda yerləşir. Dəniz səviyyəsindən 2225 metr yüksəklikdədir. Oradan dəmiryol stansiyasına (Ağstafaya) 112 verstlik maşın yoludur. Yevlax-Bərdə dəmir yolu ilə isə İstisuya Tərtər-Ağdərədən keçən yol 200 km-dir. Kəlbəcər-İstisu arası isə Tərtər çayı boyunca uzanan maşın yolu ilə 25 km-dir. 1940-cı ildə 2 sahədə (Kəlbəcər-Ağdərə, Kəlbəcər-İstisu) İstisu-Tərtər yolu çəkilmişdi.
Azərbaycan təbiətinin bilicisi, mərhum akademik Mirəli Qaşqayın gözü ilə bu yerlərə baxsaq və dili ilə desək, belə alınardı: “. . . Kəlbəcər rayonundakı İstisu mineral su bulağı təbiətin gözəl hədiyəsidir. Öz kimyəvi tərkibi və fiziki xüsusiyyətlərinə görə, bu sular dünyada məşhur olan Karlovı-Varı bulaqlarının (Çexiya)) eynidir və bəzi xüsusiyyətlərinə görə dünyada yeganədir”.
O, zamanın ən körkəmli kimyaçı alimi E. E. Karstenski Kəlbəcər ərazisindəki mineral suları yoxladıqdan sonra İstisuyun müalicəvi əhəmiyyətini daha yüksək (hətta- Karlovı-Varıdan da yüksək) qiymətləndirmiş və bu mülicə otağının təkcə bu əraziyə, Azərbaycana, SSRİ-yə deyil, dünyaya şöhrət gətirəcək bir mənbə olduğunu göstərmişdir.
İstisuyun istiliyi 58,8 0C qədərdir. Cəmi mineralların sayı 6,7 qrama çatan 1 litr suyun tərkibi göstərir ki, litium, brom, yod, mərgümüş, fosfor, sink, med, nikel, maqnezium, dəmir və s. kimyəvi maddələrlə zəngindir. Bu bulaqlardan biri 8 metrədək hündürlükdə fəvvarə vurur. Verilən məlumatlar göstərir ki, İstisu mənbələrindən hər il 3 milyard 963 mln. litr su çıxır. Sudolduran sexlər isə bunun cəmi 22 mln. litrindən istifadə edirdi.
İstisu mineral bulaqları 1138-cu ildə güclü zəlzələ zamanı yerin qabarması, çatlaması nəticəsində əmələ gəlmişdir. İstisu mineral bulaq suyu hipertermal, karbon qazlı, hidrokarbonatlı-xloridli-sulfatlı-natriumludur. İstisu mineral bulaqları fəaliyyətdə olan 12 bulaqdan ibarətdir. Kəlbəcər rayonu ərazisində yerləşən İstisu mineral suları özlərinin əlverişli qaz və kimyəvi tərkibinə, yüksək temperaturuna, böyük təbii ehtiyatlarına görə xüsusilə fərqlənir. Onun suları ilə insanın həm xarici həm də daxili xəstəlikləri müalicə etmək mümkündür. İstisu bulağı üstündə 80-ci illərdə iri kurort və mineral sudoldurma zavodu tikilmişdir. Həmin zavod sutkada 800 min litr su istehsal edirdi.
Rayonun İstisu (Kəlbəcər) qəsəbəsində keçmiş SSRİ-də Ümumittifaq əhəmiyyətli 1 və 2 nömrəli İstisu sanatoriyaları fəaliyyət göstərirdi. Hər il orada 50 min nəfər müalicə olunur və istirahət edirdi. İstisu mineral suyu rayon büdcəsinə ən çox gəlir gətirən təbii sərvətlərdən biridir. Azərbaycan neftinin çıxarılmasına külli miqdarda vəsait xərclənir. Hətta xarici şirkətlərin köməyindən də istifadə olunur. Təbii bulaq olan İstisuyun illik axımı 600 milyon litrə bərabərdir. Ancaq bu suyun cəmi 10 faizindən istifadə olunurdu. Müalicəvi əhəmiyyətinə görə Çexiyanın Karlovu Vari suyundan üstün olan İstisuya şəfa tapmaq üçün müxtəlif ölkələrdən turistlər gəlirdi.
Kəlbəcər rayonu 2 aprel 1993-cü ildə ermənilər tərəfindən işğal olunmuşdur. Kəlbəcərin işğalı zamanı rayonun 54 mindən artıq əhalisi məcburi köçkün düşmüş, 321 nəfər əsir düşmüş və ya girov götürülmüş, 511 nəfər vəhşicəsinə qətlə yetirilmiş, 97 məktəb, 9 uşaq bağçası, 116 kitabxana, 43 klub, 42 mədəniyyət evi, tarix-diyarşünaslıq muzeyi, 9 xəstəxana, 75 tibbi məntəqə, 23 ambulatoriya, 9 aptek, yüzlərlə inzibati bina, minlərlə mənzil, 100 min baş qaramal, 500 min baş qoyun-quzu, 100-lərlə maşın, texnika və s. talan edilmiş və rayonun milyardlarla manatlıq sərvəti Ermənistana daşınmışdır.
Dağlıq Qarabağ ərazisindən kənarda yerləşən, 58 min (1993) nəfər əhalisi olan Kəlbəcər rayonunun Ermənistan Silahlı Qüvvələri tərəfindən işğal edilməsi nəticəsində dinc əhaliyə vəhşicəsinə divan tutulub, yerli əhali min illər boyu yaşadığı ata-baba torpağından qovularaq didərgin salınıb.
Kəlbəcərin işğalından sonra 3205 saylı iclasda BMT Təhlükəsizlik Şurası 822 saylı Qətnamə qəbul edib. Qətnamədə bütün işğalçı qüvvələrin Kəlbəcər və Azərbaycanın digər işğal olunmuş rayonlarından dərhal çıxarılması tələb olunur. Lakin indiyədək həmin qətnamədən irəli gələn hər hansı öhdəlik yerinə yetirilməyib.
Kəlbəcər rayonunun əhalisi Azərbaycan Respublikasının 56 rayon və şəhərinin 707 yaşayış məntəqəsində qaçqınlıq şəraitində yaşayır. Kəlbəcər rayonu ərazisində qalmış 13. 000-dək fərdi mənzil, 37. 852 ha meşə sahəsi indi də talan olmaqdadır. BMT-nin və ATƏT-in prinsiplərinə zidd olaraq 1999-cu ildən Kəlbəcər rayonu ərazisində ermənilərin məskunlaşdırılmasına başlanılıb.
Kəlbəcər rayonu 25 noyabr 2020 - ci ildə Ermənistan işğalından azad olunmuşdur. Qarabağ Azərbaycandır! 
''',
    ),
    InfoModel(
      "assets/xocali.png",
      "Xocalı",
      '''Xocalı rayonu 1991-ci il noyabr ayının 26-da Əsgəran rayonu bazasında yaradılmışdır. Rayonun ərazisi 1991-1992-ci illərdə erməni silahlı qüvvələri tərəfindən işğal edilmişdir. Sahəsi 0,94 min kv. km, əhalisi 28,8 min nəfərdi (01.01.2020). Xocalı rayonu ilə Bakı arasında olan məsafə 375 kilometrdir. Rayon Laçın, Kəlbəcər, Ağdam, Xocavənd və Şuşa rayonları ilə qonşu idi. Rayonda 1 şəhər, 1 qəsəbə (Əsgəran), 50 kənd olmuşdur. Mərkəzi Xocalı şəhəridir. Kəndləri bunlardır – Almalı, Qarakötük, Ballıca, Xanyurdu, Mehdibəyli, Cəmilli, Çanaqçı, Sığnaq, Dağyurd, Daşbulaq, Badara, Xanyeri, Qayabaşı, Suncinka, Harov, Dağdağan, Xanabad, Ağgədik, Aşağı Qılıçbağ, Kosalar, Başkənd, Canhəsən, Təzəbinə, Qışlaq, Cavadlar, Yalobakənd, Qarabulaq, Dəmirçilər, Quşçubaba, Mədətkənd, Qızıloba, Aşağı Yemişcan, Xaçmaç, Yuxarı Yemişcan, Meşəli, Naxçıvanlı, Ağbulaq, Aranzəmin, Dəhrəz, Pircamal, Pirlər, Daşbaşı, Fərrux, Seyidbəyli, Ulubaba, Şuşakənd, Daşkənd, Muxtar, Sərdarkənd, Şəlvə.
Rayonun ərazisindən uzunluğu 32 km olan birinci kateqoriyalı şose yolu və Bakı-Xankəndi dəmir yolu keçirdi.
İşğala qədər rayonda 56 mədəniyyət müəssisəsi, muzeylər, texnikum, orta məktəblər, səhiyyə müəssisələri, kənd təsərrüfatı və sənaye müəssisələri, aeroport və s. fəaliyyət göstərirdi.
Əhali əsasən üzümçülük, heyvandarlıq, arıçılıq və əkinçiliklə məşğul olmuşdur.
“Xocalının səsi” rayon qəzeti 1991-ci ildən nəşr edilir.
Son illərdə baş vermiş hadisələrlə əlaqədar olaraq Fərqanədən (Özbəkistan) qaçqın düşmüş 54 məhsəti-türkü ailəsi, həmçinin Ermənistandan və Xankəndindən qovulmuş azərbaycanlıların bəziləri Xocalı şəhərində məskunlaşmışdılar.
Rayonun ərazisi əsasən dağlıqdır. Ən hündür yüksəkliyi Qızqala və Qırxqızdır (2843 m, 2827 m). Dağlıq ərazilər istisna olmaqla, iqlimi mülayim-istidir. Yüksək dağlıq əraziləri subalp və alp çəmənlərdir. Əsas çayları Badara və Qarqardır. Dağ-meşə və dağ-çəmən torpaqları mövcuddur. Ərazinin 40 %-ə qədəri fısdıq, cökə, ağcaqayın, qaraağac və s. ilə zəngindir.
Azərbaycan xalqının XX əsrdə üzləşdiyi dəhşətli faciələrdən biri də Xocalı soyqırımıdır. Xocalı faciəsi Xatın, Lidisa, Oradur soyqırımı kimi insanlıq tarixinə düşmüş qanlı olaydır.
Xocalı 1991-cı ilin oktyabrından blokadada idi. Oktyabrın 30-da avtomobil əlaqəsi kəsilmiş və yeganə nəqliyyat vasitəsi vertolyot qalmışdı. Xocalıya sonuncu vertolyot 1992-ci il yanvarın 28-də gəlmişdi. Şuşa şəhərinin səmasında mülki vertolyotun vurulması və nəticədə 40 nəfərin həlakından sonra isə bu əlaqə də kəsilmişdi. Yanvarın 2-dən şəhərə elektrik verilmirdi. Şəhər ancaq əhalinin qəhrəmanlığı və müdafiəçilərin cəsurluğu sayəsində yaşayır və müdafiə olunurdu. Şəhərin müdafiəsi əsasən atıcı silahlarla silahlanmış yerli özünümüdafiə dəstəsi, milis və Milli Ordunun döyüşçülərindən təşkil olunmuşdu.
Fevralın ikinci yarısından başlayaraq Xocalı erməni silahlı dəstələrinin mühasirəsinə alınmışdı və hər gün toplardan, ağır texnikadan atəşlərə, erməni dəstələrinin həmlələrinə məruz qalırdı.
Xocalıya hücuma hazırlıq fevralın 25-də axşam 366-ci alayın hərbi texnikasının döyüş mövqelərinə çıxması ilə başlanılmışdı. Şəhərə hücum toplardan, tanklardan, "Alazan" tipli zenit toplardan 2 saatlıq atəşdən sonra başlandı. Xocalıya üç istiqamətdən hücum aparıldığından əhali Əsgəran istiqamətində qaçmağa məcbur olmuşdu. Tezliklə aydın olmuşdur ki, bu məkrli hiylə imiş. Naxçıvanlı kəndi yaxınlığında əhalinin qarşısı erməni silahlı dəstələri tərəfindən kəsilmiş və onlar gülləborana tutulmuşlar. Qarlı aşırımlarda və meşələrdə zəifləmiş, taqətdən düşmüş insanların çox hissəsi məhz Əsgəran-Naxçıvanlı düzündə erməni silahlı dəstələri tərəfindən xüsusi qəddarlıqla məhv edilmişdir.
İkinci Qarabağ müharibəsi (27 sentyabr - 09 noyabr 2020) ərzində Xocalı rayonunun 9 kəndi Ermənistan işğalından azad olunmuşdur. Xocalı üzərində Azərbaycanın suverenliyi bərqərar olmuş, Azərbaycan Respublikasının ərazi bütövlüyü bərpa olunmuşdur. Qarabağ Azərbaycandır!
''',
    ),
    InfoModel(
      "assets/lacin.png",
      "Laçın",
      '''Laçın rayonu Azərbaycan Respublikasının cənub-qərbində, dağlıq ərazidə yerləşir. Şimaldan Kəlbəcər, şərqdən Xocalı, Şuşa və Xocavənd, cənubdan Qubadlı rayonları, qərbdən isə Ermənistan Respublikası ilə həmsərhəddir.
Dünyada ən nadir ağac sayılan qırmızı dəmirağac meşələri, çoxlu mineral suları, kobalt, uran, civə, qızıl, dəmir, müxtəlif rəngli mərmər yataqları, həddindən çox dərman bitkiləri və s. vardır.
Laçın şəhərinin yerini Tağı Şahbazi seçmiş və bu adı da ona özü vermişdir. Laçın rayonu 1924-cü ildə təsis edilmişdir. Rayon kimi yaranma tarixi 08 avqust 1930-cu ildir. Ərazisi 1.84 min km2, əhalinin sayı 78,6 min (01.01.2020) nəfərdir. Laçın rayonunda 1 şəhər (Laçın), 1 qəsəbə (Qayğı), 125 kənd vardır. Kəndləri bunlardır – Qarıkaha, Ağbulaq, Ağcakənd, Alxaslı, Arduşlu, Ağcayazı, Aşağı Fərəcan, Yuxarı Fərəcan, Bozlu, Qalaça, Bülündüz, Ayıbasar, Birinci İpək, Cağazur, Cicimli, Aşağı Cicimli, Qazıdərə, Daşlı, Hətəmlər, Kaha, Narışlar, Vəlibəyli, Əhmədli, Fərraş, Nurəddin, Fətəlipəyə, Ağanus, Ərəb, Turşsu, Unannovu, Güləbird, Hacıxanlı, Birinci Tığik, Qovuşuq, Hacılar, Hoçaz, Avazlar, Mollalar, Uludüz, Budaqdərə, İrçan, Çəmbərəkənd, Xumarta, Kamallı, Çıraqlı, Köhnəkənd, Alıcan, Əyrik, Qışlaq, Kürdhacı, Ərikli, Hacısamlı, Qarasaqqal, Qarabəyli, Korcabulaq, Lolabağırlı, Qarakeçdi, Katos, Qarıqışlaq, Qılınclı, Soyuqbulaq, Zeyvə, Qorçu, Zağaltı, Qoşasu, Alpout, Bülövlük, Qozlu, Fingə, Quşçu, Malxələf, Mazutlu, Məlikpəyə, Malıbəy, Ağoğlan, Hüsülü, Ziyrik, Mığıdərə, Xırmanlar, Dəyhan, Dəyirmanyanı, Baldırğanlı, Tərxanlı, Minkənd, Mirik, Mişni, Oğuldərə, Ağalaruşağı, Piçənis, Xaçınyalı, Köhnə Çorman, Pircahan, Alıqulu, Qaraçanlı, Seyidlər, Sadınlar, Səfiyan, Xanalılar, Suarası, Türklər, Sonasar, Mayis, Şamkənd, Bozdağan, Çorman, Ələkçi, Nağdalı, İkinci Tığik, Şəlvə, Dambulaq, İmanlar, Təzəkənd, Ərdəşəvi, Haqnəzər, Vağazin, Bozgüney, Kalafalıq, Zabux, Bəylik, Qızılca, Sus, Zerti, Ağbulaq, Şeylanlı.
Laçın rayonu ilə Bakı arasında olan məsafə 414 kilometrdir.
Laçın rayonunun 200-ə yaxın tarix mədəniyyət və memarlıq abidələri, onlarla kurqan, qala tipli arxeologiya baxımından faydalı olan abidələr, çoxlu sayda qəbirüstü abidələr, stellalar, at, qoç fiqurları, süjetli daşlar, eləcədə bu ərazi çoxlu təbii sərvətləri, qiymətli mineral suları ilə zəngin bir ərazi olmuşdur ki, 1992-ci ilin may ayının 18-dən Ermənistan Respublikasının işğalı altındadır.
İşğaldan əvvəl: 217 mədəniyyət müəssisəsi, 142 səhiyyə obyekti, 133 idarə və müəssisə, 100 ümumtəhsil məktəbi, 5 məktəbəqədər müəssisə, 5 musiqi məktəbi, 1 internat məktəbi, 1 orta texniki peşə məktəbi, 1 rabitə evi və s. vardı.
Laçın dedikdə, onu bir dəfə görən insanın gözünün qabağında insanı heyran edən gözəl bir mənzərə canlanır. Mahalın aşağı hissəsində Zəngəzur dağının ətəyində bir-birindən xeyli aralı Artız, Salaq və Mərkiz dağları, onlardan uzaqlarda Xustun, Kəpəz, Keçəldağ silsiləsi uzanır, onlardan o tərəfdə Pirdavan, Qacaran, Kiqin dağları görünür. Zəngəzur dağlarının zirvəsi bəzi yerlərdə dəniz səviyyəsindən 3906 metr yüksəkdir və həmişə qarla örtülüdür.
Laçın bölgəsi ölkələrlə, dövlətlərlə, Azərbaycanın Səfəvilər dövləti ilə, Rusiyanın hətta bir vilayəti ilə müqayisədə çox kiçik sahəyə malik bir bölgədir. Amma, Ulu Yaradan bu bölgəni elə bil özü üçün, özünün mələkləri üçün yaradıb, “eşqinin, məhəbbətinin” coşub-çağlayan vaxtı yaradıb. Gözəl meşələri, təmiz havası, saf suları, ceyranları-cüyürləri, dağ keçiləri, şəlalələri, sərt qayaları, başı ağ çalmalı dağları, dağ başında düzənləri, ucsuz-bucaqsız yaylaqları, qayalarından sallanan cürbəcür gülləri, şaxtada qaynayan isti bulaqları, dünyanın heç yerində tapılmayan təbii gül-çiçəkləri, 300-400 il yaşında qırmızı palıd ağacları, qartalları, qurd ürəkli oğulları, oğullara arxa olan –dayaq olan, kişilərin arxasını yerə qoyan qadınları, qızları var Laçının. Bir sözlə təbiət bu torpaqdan öz əsrarəngiz gözəlliyini, təbii sərvətlərini və bol-bol nemətlərini əsirgəməmişdir. Tarixən təbii şəraitinə görə burada əsasən heyvandarlıqla məşğul olsalar da - əkinçilik, arıçılıq, bağ-bostançılıq da inkişaf etmişdir. Yun, xəz materiallarından burada nə istəsən yaradırdılar. Laçının çox keyfiyyətli su mənbələri vardı. Bunlardan 20-dən artıq müalicə əhəmiyyətli bulaqlar idi. Buranın insanları çox-çox qədimlərdən bu mineral bulaqlardan müalicə məqsədi ilə istifadə etmişlər. El arasında möcüzəsinə görə bu sulara – baş suyu, göz suyu, diş suyu, yel suyu, mədə suyu və s. adlar verilmişdi. Bu su mənbələri əsasən bölgənin Minkənd, Molla-Əhmədli, Mirik və s. yaşayış məntəqələrinə yaxın idi və bu bulaqlar üzərində həmişə yeyib-içmək məqsədi ilə abadlıq yaradırdılar. Yay aylarında Qarabağın, Zəngəzurun isti yerlərindən, xüsusən Bakı və Sumqayıtda yaşayan əhali bu yerlərdə istirahət edər, müalicə alardılar.
Laçın rayonu 1 dekabr 2020-ci ildə Ermənistan işğalından azad olunmuşdur. Zəngəzur Azərbaycandır!
''',
    ),
    InfoModel(
      "assets/xocavend.png",
      "Xocavənd",
      '''Xocavənd rayonu 26.11.1991-ci ildə Dağlıq Qarabağ Muxtar Vilayəti ləğv edildikdən sonra Martuni və Hadrut rayonlarının bazası əsasında yaradılıb. Rayonun ərazisi 1. 46 min km2, əhalisi 44,1 min (01.01.2020) nəfərdir. Xocavənd rayonu ilə Bakı arasında olan məsafə 334 kilometrdir. Xocavənd rayonu 1 şəhər (Xocavənd), 2 iri qəsəbə (Hadrut, Qırmızı Bazar) və 81 kəndi birləşdirir. Kəndləri bunlardır – Şexer, Şıx Dursun, Dağdöşü, Edişə, Qırmızıqaya, Qoçbəyli, Tağaser, Vəng, Ağkənd, Axullu, Arakül, Bünyadlı, Cilən, Daşbaşı, Zərdanaşen, Müşkapat, Kiş, Köhnə Tağlar, Yemişcan, Qarqar, Xərxan, Zavadıx, Tağaverd, Çağadüz, Mülküdərə, Arpadüzü, Azıx, Zoğalbulaq, Binə, Binədərəsi, Sor, Böyük Tağlar, Bulutan, Xırmancıq, Məlikcanlı, Cəmiyyət, Çaylaqqala, Arpagədik, Petrosaşen, Çiraquz, Məmməddərə, Tsakuri, Dərəkənd, Ağcakənd, Hakaku, Qağartsi, Quzumkənd, Qarazəmi, Mirikənd Avdur, Tuğ, Ataqut, Kuropatkin, Şahyeri, Dolanlar, Edilli, Ağbulaq, Düdükçü, Əmiranlar, Gavahın, Ağbulaq, Güneyxırman, Çörəkli, Quzeyçartar, Quzeyxırman, Günəşli, Quşçular, Heşan, Xanoba, Xocavənd, Kəndxurd, Qarıtəpə, Qaradağlı, Qarakənd, Muğanlı, Salakətin, Sos, Cütcü, Susanlıq, Yenikənd, Güneyçartar.
Olduqca əlverişli coğrafi mövqeyə və şəraitə malik Xocavənd rayonu Ağdam, Ağcabədi, Füzuli, Cəbrayıl, Qubadlı, Laçın, Şuşa, Xocalı rayonları ilə həmsərhəddir.
Xocavənd toponimi 2 hissədən - Xoca sözündən və vənd komponentindən ibarətdir. Xoca sözü türk dilində «müəllim, öyrətmən» anlamındadır. Vənd komponenti İran dillərində «uşağı, nəsli, törəməsi» mənasını daşıyır.
Xocavənd rayonu əsasən kənd təsərrüfatı rayonudur. İqtisadiyyatında üzümçülük, taxılçılıq və heyvandarlıq mühüm yer tuturdu. Rayonda axan dağ çayları füsunkar gözəlliklə bərabər, bağçılıq və bostançılıq üçün əlverişli şərait yaratmışdır. Əsrlərdən bəri əhali bu torpaqlarda meyvə bağları salmış, müəyyən təsərrüfat işləri ilə məşğul olmuşlar.
Rayon Ağdam-Füzuli avtomobil yolu kənarında, dağətəyi düzənlikdədir. Relyefi əsasən dağlıqdır. Hündürlüyü təqribən 500 metrdən 2725 metrə (Böyük Kirs dağı) qədərdir.
Rayon ərazisində Bağırxan, Qırmızı Bazar, Mədə Bulağı, Baba Bulağı, Ballı Bulaq və s. onlarla istirahət zonaları var.
Özünəməxsus təbii sərvətləri, təbiət abidələri olan qədim yaşayış məskənlərindən sayılan Xocavənd rayonunda ehtiyatları 2034 min m3 olan və üzlük daşı istehsalına yararlı Ediş qabbro; ehtiyatları 989 min ton olan, əhəng istehsalına yararlı Xocavənd əhəngdaşı; proqnoz ehtiyatları 90,33 min m3/gün olan yeraltı şirin su yataqları var. Çayları (Xonaşençay, Köndələnçay, Qozluçay, Quruçay, Çaxmaqçay, Alıçay, Atautçay, Binəçay və s. ) Kür-Araz hövzələrinə aiddir.
Xocavənd rayonunda Qırmızı bazar qəsəbəsində diametri 600 sm, hündürlüyü 25 m olan 1 ədəd 1000 il və diametri 600 sm, hündürlüyü 25 m olan 1 ədəd 2000 il yaşlı Şərq çinarları təbiət abidəsi kimi qorunurdu.
Xocavənd rayonunun Qarakənd kəndində Respublikanın “Qırmızı kitab”ına düşmüş 0,5 ha III dövrün relikt növü olan, orta diametri 24 sm, hündürlüyü 12 m, yaşı 100 illik azat ağacları da mühafizə edilirdi.
Rayon Ağdam-Füzuli avtomobil yolu kənarında, dağətəyi düzənlikdədir. Relyefi əsasən dağlıqdır. Hündürlüyü təqribən 500 metrdən 2725 metrə (Böyük Kirs dağı) qədərdir.
Özünəməxsus təbii sərvətləri, təbiət abidələri olan qədim yaşayış məskənlərindən sayılan Xocavənd rayonunda ehtiyatları 2034 min m3 olan və üzlük daşı istehsalına yararlı Ediş qabbro; ehtiyatları 989 min ton olan, əhəng istehsalına yararlı Xocavənd əhəngdaşı; proqnoz ehtiyatları 90,33 min m3/gün olan yeraltı şirin su yataqları var.
Bitki örtüyündə kolluq və seyrək meşəli çəmənlər üstünlük təşkil edir. Xocavənd rayonunda Qırmızı bazar qəsəbəsində diametri 600 sm, hündürlüyü 25 m olan 1 ədəd 1000 il və diametri 600 sm, hündürlüyü 25 m olan 1 ədəd 2000 il yaşlı Şərq çinarları təbiət abidəsi kimi qorunurdu.
Xocavənd rayonunun Qarakənd kəndində Respublikanın “Qırmızı kitab”ına düşmüş 0,5 ha III dövrün relikt növü olan, orta diametri 24 sm, hündürlüyü 12 m, yaşı 100 illik azat ağacları da mühafizə edilirdi.
Xocavənd rayonu ərazisində, Salakətin kəndinin yaxın¬lığında (Quruçay vadisində) 1,5 milyon il yaşı olan Azıx mağarası, həmçinin qədim tarixə malik Tağlar mağarası, Tuğ kəndi ərazisində yerləşən V-VIII əsrlərə aid «Ritiş» qalası, Ərgünəş dağının yamacında sıldırım qayalar üzərində yerləşən «Ərgünəş» qalası, Düdükçü kəndi ətrafında XIII əsrə aid «Rzaqulu Bəy» türbəsi, Xocavənd kəndi yaxınlığında «Aşıqlı Qoşa» günbəzi, Böyük Tağlar kəndində «Alban» məbədi (1241-ci il), Tuğ kəndindəki «Qırmızı» məbəd adlı X əsrə aid tarixi memarlıq və incəsənət abidələri və s. var.
1988-ci ilin fevralından başlayan Qarabağ müharibəsində Xocavənd rayonu 145 şəhid (onların 13 nəfəri qadın, 13 nəfəri uşaqdır) vermişdir. Xocavənd rayonu 02. 10. 1992-ci ildə Ermənistan silahlı qüvvələri tərəfindən işğal olunmuşdur.
9 oktyabr 2020–ci ildə Xocavənd rayonunun Hadrut qəsəbəsi, ikinci Qarabağ müharibəsi ərzində rayonun 35 kəndi Ermənistan işğalından azad olunmuşdur. Xocavənd üzərində Azərbaycanın suverenliyi bərqərar olmuş, Azərbaycan Respublikasının ərazi bütövlüyü bərpa olunmuşdur. Qarabağ Azərbaycandır!  
''',
    ),
    InfoModel(
      "assets/qubadli.png",
      "Qubadlı",
      '''Qubadlı rayonu 14.03.1933-cü ildə yaradılmışdır. Rayonda 1 şəhər (Qubadlı) 93 kənd vardı. Sahəsi 802 km2, əhalisi 41,6 min (01.01.2020) nəfərdir. Kəndləri bunlardır - Aşağı Cibikli, Xallava, Yuxarı Cibikli, Balasoltanlı, Qaraimanlı, Padar, Başarat, Armudlu, Deşdahat, Hat, Milanlı, Çardaqlı, Əyin, Xələc, Tarovlu, Çərəli, Boyunəkər, Saldaş, Dəmirçilər, Poladlı, Dondarlı, Diləli, Müskənli, Mirlər, Göyərcik, Əliquluuşağı, Fərcan, Göyyal, Hərtiz, Zor, Bəxtiyarlı, Saray, Hal, Ballıqaya, Qəzyan, Məmər, Mollalı, Həmzəli, Çaytumas, Əfəndilər, Yusifbəyli, Xanlıq, Xocahan, Qilican, Tinli, Xocik, Mərdanlı, Qaracallı, Qarağac, Qarakişilər, Qaralar, Hüseynuşağı, Kavdadıq, Qayalı, Abdalanlı, Ləpəxeyranlı, Mahmudlu, Mahruzlu, Muradxanlı, Muğanlı, Məlikəhmədli Qundanlı, Alaqurşaq, Davudlu Eyvazlı, Gürcülü, Qədili, Məzrə, Sarıyataq, Tatar, Qaraqoyunlu, Qiyaslı, Teymur, Müskənli, Balahəsənli, Xıdırlı, Ulaşlı, Altınca, Əbilcə, Yuxarı Xocamsaqlı, Aşağı Xocamsaqlı, Mehrili, Yuxarı Mollu, Aşağı Mollu, Mollabürhan, Zilanlı, Kürd Mahruzlu, Seləli, Novlu, İşıqlı, Həkəri, Cılfır, Seytas, Göyər Abbas, Xəndək.
Qubadlı rayonu ilə Bakı arasında olan məsafə 403 kilometrdir. Qubadlı rayonu Azərbaycan Respubikasının cənub-qərbində, Qarabağ yaylasının cənub şərqində yerləşir. Ermənistan Respublikası ilə (120km) Xocavənd rayonu ilə (45km), Laçın, Cəbrayıl və Zəngilan rayonları ilı həmsərhəddir.
Qubadlı rayonunun təbiəti olduqca gözəldir. 1969-cu ildə burada dövlət yasaqlığı yaradılmışdır. Rayonda 13. 2 min hektar meşə sahəsi vardır. Palıd bu meşələrin arxası, vələs dövləti, alma, armud, fındıq, əzgil, zoğal, yemişan. . . sərvəti, dağ çayları, şəlalələr, buz bulaqlar şöhrəti, qara gözlü əliklər, xınalı kəkliklər, qırqovullar, turaclar, göyərçinlər. . . gözəlliyi idi.
Rayon ərazisindən iki böyük dağ çayı keçir. Həkəri-Bərgüşad. Həkəri çayı öz mənbəyini Kəlbəcərdən götürüb. Araza qovuşana kimi bir çox dağ çayları ona qovuşur.
Bərgüşad çayının mənbəyi isə Ərikli dağlarından başlayır. Bərgüşad öz gücünü dağ bulaqlarından süzülüb gələn Dəli çay, Şəki çayı, Sisyan çayı, Taxtakörpü çayı, Daşlı dərə çayı, Bəxtiyarlı və Ağa çaylarından alır. Bərgüşad çayı da öz Həkəri çayı kimi Araza tökülür. Hər iki çay rayonun Qaralar kəndinin yaxınlığında birləşir.
Rayonun bir hissəsi aran olsa da, əsas hissəsi dağlıqdır. Dağlıq yerlər meşə örtüyünə bürünmüşdür. Rayonun Hərtiz və Səngər dağlarındakı şəfalı bulaqları can dərmanıdır. Qubadlılar heyvandarlıqla, tütünçülüklə və taxılçılıqla məşğul olurdular. Qubadlıda hələ istifadə olunmamış böyük əqiq yatağı da var. Bundan başqa mərmər karxanası da var idi.
Qubadlı və onun ətrafında yerləşən kəndlər hələ XVIII əsrdə Qarabağ inzibati ərazisinə daxil idi. Sonralar Zəngəzur mahalına daxil olan Qubadlı 1868-ci ildə Yelizavetpol quberniyası yaranandan sonra Zəngəzurun tərkibinə daxil olmuşdur. Ermənistanın Gorus, Qafan rayonları və Zəngilan, Cəbrayıl, Laçın və Xocavənd rayonları ilə həmsərhəddir.
Qubadlı şəhəri Qarabağ yaylasının cənub-şərqində, Bazar-çayın sahilində yerləşir. Şəhərdə 62 idarə və müəssisə fəaliyyət göstərirdi. Burada asfalt zavodu, inkubator-quşçuluq fabriki, daş karxanası, texniki-təchizat idarəsi, tikiş fabriki, Azərbaycan “Neftqazavtomat” təcrübə zavodu və başqa istehsal xarakterli müəssisələr də var idi.
Qubadlı rayonunda 21 orta, 26 səkkizillik, 15 ibtidai məktəb, bir əyani-qiyabi orta məktəb var idi. Xanlıq kəndindəki 126 №-li orta texniki peşə məktəbində hər il 300 nəfər şagird müxtəlif peşələrə yiyələnirdi.
Qubadlı rayonunda 300 yerlik 4 xəstəxana və 33 səhiyyə müəssisəsi fəaliyyət göstərirdi.
Rayonda 111 mədəni maarif müəssisəsi, o cümlədən 60 kitabxana, 10 mədəniyyət evi, 28 klub, 6 avtoklub, 23 kino qurğusu fəaliyyət göstərirdi. 125 ticarət, 96 ictimai-iaşə, 25 məişət xidməti müəssisəsində əhaliyə xidmət göstərirdi.
Rayonda 21 rabitə müəssisəsi vardı. Qubadlı qəsəbəsində 1200, Hal, Muradxanlı kəndlərinin hər birində 150, Teymur Müskanlı, Balasultanlı, Çardaxlı, Aşağı Mollu kəndlərinin hər birində 100, Qayalı kəndində 50 nomrəli ATS fəaliyyət göstərirdi.
Qubadlı rayonu 31 avqust 1993-cü ildə Ermənistan silahlı birləşmələri tərəfindən işğal olunmuşdur.
İşğaldan qabaqkı son illərdə qəsəbə və kəndlərdə onlarla yeni ictimai və yaşayış binaları tikilmiş, bağlar, xiyabanlar, meydanlar, körpülər salınmış, yollar çəkilmişdir. Qəsəbədə 1176, Çəpəli, Dondarlı, Mahruzlu kəndlərinin hər birində 422, Muradxanlı kəndində 325, Balasoltanlı, Çardaxlı, Qaracallı kəndlərinin hər birində 192, Göyərçik kəndində 164 yerlik orta, Qayalı kəndində 216, Dəmirçilər, Xəndək kəndlərinin hər birində 192, Qarakişilər, Tarovlu, Aşağı Xocasamlı kəndlərinin hər birində 164 yerlik səkkizillik, Mərdanblı, Padar, Qiyaslı, Abdalalanlı, Mərlər kəndlərində ibtidai məktəb binaları da işgaldan əvvəl istifadəyə verilmişdir.
Rayon mərkəzindəki müasir tipli xəstəxana şəhərciyi, ATS, ticarət mərkəzi, univermaq, universam, bazar, mehmanxana, kitab evi, Mahruzlu kəndindəki poliklinika, Qaralar kəndindəki ambulatoriya, Xocik, İşıqlı, Diləli, Müskanlı kəndlərindəki kitabxana binaları da işğaldan qabaq inşa edilmişdir. Bu müddət ərzində rayon mərkəzində 30-a qədər inzibati bina tikilib istifadəyə verilmişdir.
Həmçinin işgaldan əvvəl rayon mərkəzində Əliquluşağı, Həkəri (Zəngilan rayonu) Xanlıq, Əyin, Fərcan, Mirlər, Dəmirçilər, Hərtiz, Çərəli, Muradxanlı, Qaracallı, Eyvazlı və Yuxarı Mollu ilə birləşdirən yeni asfalt və şosse yollar çəkilmiş, köhnə yollar genişləndirilmişdir. Xanlıq-Yuxarı Mollu, Ulaşlı-Mahruzlu, Qəzyan-Xocahan və başqa kənd arası yollar öz əvvəlki görkəmini büs-bütün dəyişmişdir. Qubadlı-Dondarlı, Sariyataq-Padar, Qralar-Mahruzlu, Teymur Müskanlı-Balahəsənli, Mahmudlu-Hacılı körpüləri həsrətli sahilləri bir-birinə qovuşdurduğu kimi, yolçulara da qol-qanad vermişdir. Səngər dağının səfalı bir güşəsində cənnət misallı Armudlu bağında tikilən ponsionat hamını sevindirmişdir. Qubadlılar öz sevimli qəsəbə və kəndlərində tikinti abadlıq işlərini həvəslə davam etdirirdilər. . .
25 oktyabr 2020–ci ildə Qubadlı şəhəri, ikinci Qarabağ müharibəsi ərzində rayonun 41 kəndi Ermənistan işğalından azad olunmuşdur. Qubadlı rayonu üzərində Azərbaycanın suverenliyi bərqərar olmuş, Azərbaycan Respublikasının ərazi bütövlüyü bərpa olunmuşdur. Zəngəzur Azərbaycandır! 
''',
    ),
    InfoModel(
      "assets/zengilan.png",
      "Zəngilan",
      '''Azərbaycan Respublikasının cənub-qərbində Ermənistan və İranla sərhəddə Bakı-Culfa-Naxçıvan magistral dəmir və şose yolları üzərində strateji cəhətdən böyük əhəmiyyət kəsb edən bir mövqedə yerləşir.
Rayonun ərazisi müxtəlif dövrlərdə ayrı-ayrı inzibati ərazi bölgülərinə məruz qalmışdır. Rusiyanın işğalı zamanı 1828-ci ilə qədər bölgənin ərazisinin Bəsitçaydan qərbə tərəf hissəsi Naxçıvan, şərqə tərəf hissəsi isə Qarabağ xanlığının tərkibinə idi.
XIX əsrin əvvəllərində Rusiyanın Cənubi Qafqazı işğal etməsindən sonra yeni ərazi-inzibati bölgüsü aparılır. 1868-ci ildə Yelizavetpol quberniyası yaradılır. Onun tərkibində Şuşa, Yelizavetpol və Zəngəzur qəzaları yaradılır. Yeni bölgüyə əsasən Zəngilan rayonunun ərazisi Zəngəzur qəzasına daxil edilir.
1925-ci ilin sənədlərində Zəngilan Cəbrayıl qəzası tərkibində göstərilir. Xəritədə Zəngilanın Genlik, Aladin, Dəlləkli qeyd olunur.
1929-cu ildə ZSFSR-nın qərarı ilə Zəngilan rayonunun Nüvədi, Toğud, Ernəzir kəndləri 1946-cı ildə isə 4 min hektar meşə sahəsi Azərbaycan Respublikasından alınıb Ermənistan Respublikasına bağışlandı.
Son iki yüz ildə vahid sərhəddə malik olmayan Zəngilan 1930-cu ilin avqust ayının 8-də müstəqil rayon kimi formalaşır və dəqiq müəyyən olunmuş ərazisi olur. Ərazisi – 0,71 min km2, əhalisi 41,6 min (01.01.2020) nəfərdir.
1967-ci ildə Zəngilana şəhər statusu verildi. Zəngilan rayonunda bir şəhər, 5 qəsəbə (Ağ oyuq, Mincivan, Bartaz, Ağbənd, Həkəri) və 79 kənd olmuşdur. Kəndləri bunlardır: Beşdəli, Genlik, Keçikli, Malatkeşin, Sarıqışlaq, Birinci Ağalı, İkinci Ağalı, Üçüncü Ağalı, Birinci Alıbəyli, Xumarlı, İkinci Alıbəyli, Sarıl, Bartaz, Qarqulu, Tatar, Tiri, Şəfibəyli, Məşədi İsmayıllı, Şərikan, Bürünlü, Yuxarı Yeməzli, Rəbənd, Yenikənd, Zəngilankənd, Cahangirbəyli, Turabad, Vəliqulubəyli Canbar, Ağkənd, Dərəli, Günqışlaq, Qazançı, Pirveys, Yuxarı Çöpdərə, Baharlı, Dəlləkli, Sobu, Böyük Gilətağ, Aladin, Dərə Gilətağ, Mirzəhəsənli, Üdgün, Şamlı, Vənədli, Hacallı, Seyidlər, Vejnəli, Ağbənd, Əmirxanlı, Qıraq Müşlan, Məlikli, Muğanlı, Xurama, Muğanlı, Şərifan, İsgəndərbəyli, Ağakişilər, Ağbis, Məmmədbəyli, Babaylı, Ördəkli, Qaradərə, Qaragöz, Rəzdərə, Kolluqışlaq, Şatarız, Şayıflı, Aşağı Gəyəli, Qaragöl, İçəri Müşlan, Tağlı, Yusiflər, Aşağı Yeməzli, Orta Yeməzli, Quyudərə Xəştab, Sarılı Xəştab, Zərnəli, Havalı, Nəcəflər.
Zəngilan rayonu coğrafi mövqeyinə, torpaq və iqlim xüsusiyyətinə görə füsunkar gözəlliyə, zəngin təbiətə malikdir. Rayonun ərazisi orta və alçaq dağlıq sahədə yerləşərək mürəkkəb və dərəli-təpəli səth quruluşuna malikdir. Şimal-qərbdən əraziyə daxil olan Bərgüşad silsiləsi (Süsən dağı, 1304 m) alçalaraq Bazarçayla Oxçuçay arasında Ağ Oyuq maili düzünü (hündürlüyü 400-600 m) əmələ gətirir. Şimal-şərqdə Qarabağ silsiləsinin Araz və Həkəri çaylarına tərəf alçalan yamacları təpəli Gəyən (Geyan) çölünə keçir. Qərbdə Mehri (Mehri-Güney) silsiləsinin şərq kənarı Bartaz dağı (2270 m) yerləşir.
Əsrin əvvəllərində rayon mərkəzinin yerləşdiyi ərazi əsasən bəylərin çəltik zəmilərindən və onların özlərinə məxsus yaşayış evlərindən ibarət idi. Zəngilan şəhəri 4 kilometrlik bir məsafədə Oxçu çayın sağ sahilində, Çeşməgözlü deyilən bir yerdən cənuba doğru əhəng quyularına qədər bir ərazidə salınmışdı. Bu şəhərin özünün bir çox məhəllələri vardır. Çeşməgözlü, Köhnə Pirçivan, MTS məhəlləsi, Məscid düzü, şaftalı dərəsi, Kirdəzir dərəsi, Bağırsaq dərə, Muncuqlu dərə, Rayşelk (ipək idarəsi olan yer) və s. məhəllələri vardır.
Rayonun bir tarixi qurum kimi iqtisadi inkişafı sovet hakimiyyəti illərində geniş vüsət almışdır. Eyni zamanda məhz bu dövrdə rayona daha çox mənəvi zərbə vurulmuşdur.
İşğala qədər rayon əsasən tütünçülük və üzümçülüklə məşğul idi. Heyvandarlıq, ipəkçilik, taxılçılıq da inkişaf etmişdir.
Zəngilan rayonundan 13 nəfər sovet imperiyasının ən yüksək dövlət mükafatına – Sosialist Əməyi qəhrəmanı adına layiq görülmüşdü. Bu hadisə bütün dünyaya səs salmışdı. Buna görə bölgə “Qızıl Zəngilan” adı ilə tarixə düşmüşdü.
Rayonun ərazisindən Bakı-Yerevan dəmir yolu (Mincivandan Qafana yol ayrılır), İmişli-Laçın və Bakı-Şərur magistral şose yolları keçirdi. Zəngilan rayonu ilə Bakı arasında olan məsafə 385 km-dir.
Özünün bir qurum kimi mövcud olduğu 63 ildə (işğala qədər) bu bölgə hansı müsibətlərə düçar olmadı?! Özünün 63 illik son tarixində bu bölgə elə ilk illərdən zorla yaradılan kollektivləşmə, 37-ci il həbsləri, 1941-45-ci illər müharibəsini də yaşadı. Rayon əhalisinin bir qisminin qohum-əqrəbası Arazın o tayında qalmış, əlaqələri kəsilmişdi. Qardaş qardaşdan, ana balasından ayrı düşmüşdü.
Zəngilanın sözünü deyən adamların 1930-cu illərdə bir qisminin sürgün olunması (Sibir, Orta Asiya, Qazaxıstan), bir qisminin isə qəddarlıqla güllələyib xəndəyə salınması, ölməyənlərin günlərlə inilti səsləri (Kənd Zəngilan: o vaxt rayon mərkəzi burada yerləşirdi) gəlirdi. Sürgün dövrü qurtardıqdan sonra da geri qayıdan adamları öz doğma yurdlarına buraxmırdılar.
Oz mövcudluğunun son illərində bu bölgə analoqu olmayan 1992-ci ilin dekabrında baş verən Şayıflı qırğınını və bir də nəhayət, 1993-cü ilin 27 oktyabrını yaşadı.
1993-cü ilin oktyabr ayında Ermənistan qoşunları tərəfindən işğal olunanadək əhalisi 32. 6 min nəfər (01. 01. 1989) olmuşdur. İşğaldan qabaq rayonda 10453 yaşayış evi, 28200 yardımçı bina, 195 inzibati bina, 870 təsərrüfatların yardımçı binaları, 128 mədəniyyət müəssisəsi, 123 təhsil müəssisəsi, texniki peşə məktəbi, 64 səhiyyə müəssisəsi, Qotursu sağlamlıq zonası, 80 rabitə müəssisəsi, 7 səyyar avtoklub, 21 kino qurğu, 2 diyarşünaslıq muzeyi, 142 ticarət obyekti, 49 ictimai-iaşə obyekti, 2 Şərab zavodu, Konserv zavodu, Toxuculuq sexi, Kərpic zavodu, Çörəkbişirmə zavodu, Çınqıl zavodu, 2 Asfalt zavodu, Yazı düzü Su nasos stansiyası kompleksi, 3 Su nasos stansiyası, 8 Dəmir yol vağzalı, Mincivan Depo, Quşçuluq fabriki, Mal-qara kökəltmə kompleksi, 3400 hektar üzüm bağları, 6 süni su tutarları olmuşdur.
Rayon mərkəzində yerləşən Muzeydə yüzlərlə eksponat var idi. Onlar xalqımızın uzaq keçmişindən bu günümüzə qədər olan həyat tərzini, məişət və mədəniyyətini əks etdirirdi.
Füzuli və Cəbrayıl rayonları işğal olunduqdan sonra zəngilanlılar 67 gün tam mühasirə şəraitində ermənilərlə vuruşmuşdur. 25-29 oktyabr 1993-cü ildə Zəngilan rayonunun əhalisi son anadək vuruşaraq Araz çayını keçmiş, İran İslam Respublikasının ərazisi ilə Azərbaycanın müxtəlif rayonlarında məskunlaşmışlar.
20 oktyabr 2020–ci ildə Zəngilan şəhəri, ikinci Qarabağ müharibəsi ərzində rayonun Mincivan, Ağbənd, Bartaz qəsəbələri, Bartaz, Sığırt, Şükürataz və daha 5 adsız yüksəklikləri və 52 kəndi Ermənistan işğalından azad olunmuşdur. Zəngilan rayonu üzərində Azərbaycanın suverenliyi bərqərar olmuş, Azərbaycan Respublikasının ərazi bütövlüyü bərpa olunmuşdur. Zəngəzur Azərbaycandır! 
''',
    ),
    InfoModel(
      "assets/cebrayil.png",
      "Cəbrayıl",
      '''Cəbrayıl rayonu Azərbaycan Respublikasının cənubunda Kiçik Qafqaz dağlarının qoynunda yerləşir. Cənub tərəfdən İran İslam Respublikası, cənub-qərbdən Zəngilan, qərbdən Qubadlı, şimaldan Xocavənd, şərqdən isə Füzuli rayonları ilə həmsərhəddir. Cəbrayıl rayonu ilə Bakı arasında olan məsafə 338 kilometrdir.
Cəbrayıl 08.08.1930-cu ildə inzibati rayon statusu almışdır. Ərazisi 1.05 min km2, əhalisi 81,7 min (01.01.2020) nəfərdir. Rayon 1 şəhər (Cəbrayıl), 4 qəsəbə (Xələfli, Xudafərin, Qumlaq, Mahmudlu) və 92 kənddən ibarət idi. Kəndləri bunlardır – Xubyarlı, Xudaverdili, İmambağı, Qurbantəpə, Şahvələdli, Yarəhmədli, Balyand, Xələfli, Qaracallı, Yuxarı Mərcanlı, Böyük Mərcanlı, Cocuq Mərcanlı, Çərəkən, Əfəndilər, Papı, Dağ Tumas, Çələbilər, Qarağac, Sofulu, Hacılı, Hüseynalılar, Kavdar, Mirək, Tulus, Horovlu, Çapand, Safarşa, Hovuslu, İsaqlı, Qalacıq, Doşulu, Mahmudlu, Yuxarı Maralyan, Qazanzəmi, Çullu, Dağ Maşanlı, Əsgərxanlı, Söyüdlü, Qumlaq, Dərzili, Məstalıbəyli, Quycaq, Nüzgar, Şəybəy, Maşanlı, Alıkeyxalı, Mehdili, Çaxırlı, Minbaşılı, Ağtəpə, Daş Veysəlli, Sədi, Sarıcallı, Əmirvarlı, Məzrə, Yuxarı Məzrə, Sirik, Aşağı Sirik, Molla Həsənli, Xanağabulaq, Şahvəlli, Göyərçin Veysəlli, Hacı İsaqlı, Qoşabulaq, Qovşudlu, Niyazqulular, Tinli, Şükürbəyli, Dəjəl, Fuğanlı, Həsənqaydı, Şıxalıağalı, Qışlaq, Karxulu, Tatar, Aşağı Maralyan, Şıxlar, Cəfərabad, Kürdlər, Daşkəsən, Yuxarı Nüsüs, Süleymanlı, Niftalılar, Yanarxac, Quşçular, Keçəl Məmmədli, Qərər, Soltanlı, Aşıq Məlikli, Nüsüs.
Cəbrayıl rayonunun adı rayonun mərkəzi olan Cəbrayıl kəndinin adından götürülmüşdür. Cəbrayıl kəndinin əsasını qoymuş Cəbrayıl ata VIII əsrdə yaşamış Sultan Əhməd adlı bir hökmdarın yaxın adamlarından biri olmuş və Ziyarət dağından Araz çayına qədər ərazilər Cəbrayıl ataya və onun övladlarına məxsus olub.
Cəbrayıl rayonunun ərazisi sement, mərmər, mişar daşı və digər qiymətli tikinti materialları ilə zəngindir. Dəmir filizi, hətta neft yataqlarının olduğu da məlumdur. Əhali əsasən üzümçülük, heyvandarlıq, taxılçılıq, baramaçılıqla məşğul olurdu. Elmin, mədəniyyətin, maarifin inkişafı yüksək səviyyəyə çatmışdı. Rayonda 510 çarpayılıq xəstəxanalarda 92 həkim, 432 orta ixtisaslı tibb işçisi, 72 məktəbdə 1660 nəfərdən çox müəllim, 3 musiqi məktəbi, 12 mədəniyyət evi, 32 klub, 10 mədəni çadır və avtoklub, 78 kitabxana və 1 muzeydə 508 mədəniyyət işçisi çalışırdı. Rayon Tarix-diyarşünaslıq muzeyində 20 mindən yuxarı eksponat vardı. Rayonda 8 sənaye müəssisəsi, 42 kolxoz, Kökəltmə birliyi, Quşçuluq fabriki fəaliyyət göstərirdi.
Azərbaycanda eramızın I əsrindən yaradılmış kəhriz şəbəkəsindən Cəbrayılda daha geniş şəkildə istifadə olunurdu. Respublikamızda olan 813 kəhrizin 118-i Cəbrayılın payına düşür. O cümlədən rayonda 360-dan çox dişgöynədən, təbii minerallarla zəngin bulaqlar vardır. Rayon ərazisindəki iki böyük suvarma kanalı – “Teymur Quliyev” və “Maralyan” kanalları kənd təsərrüfatının intensiv inkişafını təmin edirdi. Rayonda 4039 hektar meşə zolağı, 58585 hektar əkin sahəsi, 1079 hektar bağ sahəsi var idi.
Cəbrayılda xalçaçılıq (ayrıca Cəbrayıl xalça məktəbi var), xüsusi "Qasımuşağı", "Kürd", "Qaraqoyunlu", "Bəhmənli" adlı xovlu, zili, çuval, çul, məfrəc, heybə, xurcun, vərni, asmalıq, palaz, kilim, cecim kimi xovsuz xalçaları ilə məşhur olmuşdur.
Cəbrayıl rayonunun ərazisi maddi və mədəni abidələrlə zəngindir. Bunlardan Dağ-Tumas kəndi yaxınlığında yerləşən "Divlər Sarayı" mağarası, Qalacıq kəndindəki "Məscid Təpəsi", "Canqulu" və "Qumtəpə" kurqanları, Tatar kəndi yaxınlığındakı Qızılqaya dağındakı Sigeon tikintisi, ġıxlar kəndi yaxınlığında "ġəhərcik qalıqlar", "Qışlaq yerləri", Diri dağındakı Mazannənə, Mərmər nənə məqbərələri kimi arxeoloji, Doğtumas kəndindəki "Başıkəsik Gümbəz", Sirik kəndindəki "Qala", Diri dağındakı "Qız qalası", Xudafərin körpüləri, Çələbilər kəndindəki Məscid kompleksi, rayon mərkəzindəki "Sultan Məcid hamamı", şıxlar kəndindəki "Dairəvi Türbə", Xubyarlı kəndindəki "Dairəvi" 8 guşəli türbələr və məqbərələr, türk qəbiristanlığındakı türbə və məqbərələrin hər biri nəsildən-nəsilə ötürülmüş canlı tarixdir. Rayonun ərazisində çoxlu yazılı abidələr vardır ki, bunlardan da Ağoğlandakı Orxan yazılı abidəsi xüsusilə qiymətlidir.
Cəbrayıl aşıqların ulu babası sayılan Aşıq Qurbaninin, Aşıq Pərinin, Muğrum Kərimin, Aşıq Humayın, Aşıq Abdullanın və b. bu kimi el sənətkarlarının vətənidir.
Cəbrayil rayonu 1993-cü il avqust ayının 23-də əzəli və əbədi düşmənlərimizin tapdağı altına keçdi. 1050 kv km-i əhatə edən 52000 nəfər əhalisi olan rayon ərazisi və bu ərazilərdə birlikdə 72 ümumtəhsil məktəbi, 8 xəstəxana, 132 tarixi abidə, 150 mədəniyyət ocağı, 100-ə yaxın kənd büsbütün ermənilərin işğalına məruz qaldı, vəhşicəsinə dağıdıldı. Qarabağ müharibəsində 362 nəfər şəhid olmuş, 191 nəfər əlil olmuşdu. 6 nəfər Azərbaycanın Milli Qəhrəmanı adına layiq görülmüşdür.
Bundan başqa vaxtilə Cəbrayıldan 7 nəfər Sosialist Əməyi Qəhrəmanı, 1 nəfər Sovet İttifaqı Qəhrəmanı adına layiq görülmüşdür.
4 oktyabr 2020–ci ildə Cəbrayıl şəhəri, ikinci Qarabağ müharibəsi ərzində rayonun 90 kəndi  Ermənistan işğalından azad olunmuşdur. Cəbrayıl rayonu üzərində Azərbaycanın suverenliyi bərqərar olmuş, Azərbaycan Respublikasının ərazi bütövlüyü bərpa olunmuşdur. Qarabağ Azərbaycandır!
''',
    ),
    InfoModel(
      "assets/fuzuli.png",
      "Füzuli",
      '''Rayonun əsası 1827-ci ildə qoyulmuş və ilkin adı Qarabulaq olmuşdur. Füzuli 08.08.1930-cu ildə inzibati rayon statusu almış və Qaryagin adlandırılmışdır. 1959-cu ilin aprelində böyük şairimiz Məhəmməd Füzulinin anadan olmasının 400 illiyi şərəfinə Qaryagin rayonunun adı dəyişdirilərək Füzuli rayonu adlandırılmışdır. Tarixi 1827-ci ildən hesablansa da, Azıx mağarasındakı tapıntılar buranın ən qədim insan məskəni olduğunu sübut edir.
Füzuli Qarabağ dağ silsiləsinin cənub şərq ətəklərindən Araz çayına qədər maili düzənlik və alçaq sahələri əhatə edir. Cənub-qərbdə Cəbrayıl, şimalda Xocavənd, Ağcabədi, şərqdə Beyləqan rayonları və cənubda Araz çayı boyunca İranla həmsərhəddir. Rayon ərazisindən axan Quruçay, Köndələnçay, Qozluçay, Çərəkən çayları Araz hövzəsinin çaylarıdır.
Füzuli rayonunun ərazisi 1.39 min km2, əhalisi 133,8 min (01.01.2020) nəfərdir. Rayonda 2 şəhər (Füzuli, Horadiz), 11 qəsəbə (yeni salınmış 1-11№-li Qayıdış qəsəbələri), 82 kənd vardı. Kəndləri bunlardır – Alxanlı, Arayatlı, Babı, Mollaməhərrəmli, Aşağı Seyidəhmədli, Şükürbəyli, Araz Dilağarda, Şəkərcik, Şıxlı, Böyük Bəhmənli, Cuvarlı, Çimən, Xələfşə, Dədəli, İşıqlı, Qarğabazar, Yuxarı Yağlıvənd, Yuxarı Aybasanlı, Yal Pirəhmədli, Dilağarda, Dördlər, Qobu Dilağarda, Dövlətyarlı, Qərvənd, Zərgər, Yuxarı Əbdürrəhmanlı, Aşağı Əbdürrəhmanlı, Kürdlər, Əhmədalılar, Qazaxlar, Mirzənağılı, Əhmədbəyli, Araz Zərgər, Qarabağ, Murtuzalılar, Gecəgözlü, Üçüncü Mahmudlu, Horadiz, Dördçinar, Hüngütlü, Kərimbəyli, Aşağı Yağlıvənd, Yuxarı Kürdmahmudlu, Aşağı Kürdmahmudlu, Qacar, Divanalılar, Qaraxanbəyli, Qaraməmmədli, İkinci Mahmudlu, Merdinli, Qarakollu, Gorazıllı, Xatınbulaq, Qaradağlı, Saracıq, Yuxarı Rəfədinli, Yuxarı Güzlək, Qoçəhmədli, Arış, Mollavəli, Sərdarlı, Üçbulaq, Govşatlı, Şıxımlı, Aşağı Veysəlli, Yuxarı Veysəlli, Ağbaşlı, Yuxarı Seyidəhmədli, Birinci Mahmudlu, Mirzəcamallı, Ələsgərli, Hüseynbəyli, Seyidmahmudlu, Pirəhmədli, Aşağı Güzlək, Aşağı Rəfədinli, Mandılı, Musabəyli, Bala Bəhmənli, Qorqan.
Rayon iqtisadiyyatının əsasını kənd təsərrüfatı təşkil edib. Bu da məhsuldarlıq baxımından kənd təsərrüfatına yararlı boz, şabalıdı, boz –qəhvəyi torpaq sahələrinin olması ilə izah edilir. İşğala qədər rayonda taxılçılıq, heyvandarlıq, üzümçülük, qoyunçuluq, quşçuluq, baramaçılıq geniş inkişaf edib. Rayonda 65 kolxoz və sovxoz, 12 fermer təsərrüfatı, 11 üzüm emalı müəssisəsi və s. vardı. Kənd təsərrüfatına yararlı torpaqlar 85 min hektar idi. 50,9 min ha otlaq sahələri var idi. Rayonda Köndələn çayı üzərində Köndələn su anbarı tikilmiş, suvarma kanalları çəkilmişdir. Suvarılan torpaqlar 24 min hektardı. İşğaldan əvvəl təsərrüfatlarda 17. 6 min baş qaramal, 70 min baş qoyun və keçi saxlanılırdı. Kənd təsərrüfatı ilə yanaşı, rayonda tikinti tresti, 6 nəqliyyat təşkilatı, 13 sənaye müəssisəsi və s. fəaliyyət göstərirdi.
Mədəniyyətin inkişafına görə, ölkənin digər bölgələrindən geri qalmayan Füzuli rayonunda işğala qədər 90 kitabxana, 20 mədəniyyət evi, 79 klub, 20 kinoqurğu, 2 muzey, xalq və dövlət dram teatrları, istirahət parkları fəaliyyət göstərib. Təhsil və səhiyyədə də yaxşı göstəricilərə malik rayonda 685 çarpayılıq 13 xəstəxana, 17 həkim məntəqəsi, 30 feldşer–mama məntəqəsi, vərəm, dəri və zöhrəvi xəstəlikləri dispanseri, texnikum, 86 ümumtəhsil məktəbi, 2 texniki peşə məktəbi, 65 məktəbəqədər müəssisə, stadion, və s. obyektləri olub.
Eləcə də güclü kadr potensialı, yüksək intellektə malik ziyalıları, görkəmli alimləri ilə respublikamızda ad-san qazanmışdır. Əməyə bağlılıq, halal zəhmət də füzulilərin həyat tərzi olmuşdur. Bu torpağın yetirməsi Şamama Həsənova iki dəfə Sosialist Əməyi Qəhrəmanı adına layiq görülmüşdür. Füzulidə 300-dən artıq elmlər namizədi və doktoru yetişmişdir.
Füzuli rayonu həm də yaşı minilliklərə gedib çıxan Azıx mağarası, Quruçay mədəniyyəti, tarixi və memarlıq abidləri ilə tanınır.
Füzuli rayonu 23 avqust 1993-cü ildə Ermənistan silahlı qüvvələri tərəfindən işğal olunmuşdur.
1994-cü ildə aparılan uğurlu hərbi əməliyyatların sayəsində rayonun 82 yaşayış məntəqəsindən 23-ü azad edilmiş, bu gün 65962 füzulili doğma yurd-yuvalarında yaşayır. 55038 nəfər məcburi köçkün Bakı şəhəri və Respublikamızın 50 şəhər və rayonunda məskunlaşıb. Füzulidə bu gün ermənilər zəbt etdiyi torpaqlarımızda ekoloji terrorla yanaşı, rayonun XII əsrə gedib çıxan qəbristanlığını, XVII əsrə aid Mirəli türbəsini, Cəlil türbəsini, XIX əsrdə tikilmiş məscidi, İmamzadə türbəsini və qədim körpüləri darmadağın edərək vandallıq etmişlər. Qeyd edək ki, Qarabağ savaşında Füzuli rayonundan 1100-dən çox şəhid, 1550 nəfər əlil, 181 nəfər itkin düşmüşdür. Füzuliyə erməni təcavüzü nəticəsində 36361 nəfər uşaq zərər çəkmiş, onlardan 155 nəfəri yetim qalmışdır. 8 nəfər Azərbaycanın Milli Qəhrəmanı adına layiq görülmüşdür.
Müharibənin əsas ağırlığını Qacar, Divanlılar, Yuxarı Veysəlli, Aşağı Veysəlli, Qaradağlı, Üçbulaq, Arış, Qoçəhmədli, Cuvarlı, Güzdək, Gorazıllı, Cəmilli, Dilağarda, Yağlıvənd, Govşad, Xələfşə, Mollavəli kəndlərinin əhalisi çəkmişlər.
Hazırda rayonun işğaldan azad olunmuş ərazisində 1 şəhər (Horadiz), 11 qəsəbə, 21 kənd vardır. Qəsəbələrdən 11-i respublika Prezidentinin Fərmanları ilə Dövlət Neft fondundan ayrılmış vəsait hesabına işğaldan azad olunmuş ərazidə salınmışdır.
17 oktyabr 2020–ci ildə Füzuli şəhəri, ikinci Qarabağ müharibəsi ərzində rayonun 53 kəndi Ermənistan işğalından azad olunmuşdur. Füzuli rayonu üzərində Azərbaycanın suverenliyi bərqərar olmuş, Azərbaycan Respublikasının ərazi bütövlüyü bərpa olunmuşdur. Qarabağ Azərbaycandır! 
''',
    )
  ];

  @override
  Widget build(BuildContext context) {
    return Container(
      child: ListView.builder(
        physics: BouncingScrollPhysics(),
        itemCount: data.length,
        itemBuilder: (ctx, index) {
          InfoModel infoModel;
          return ListVidget(data[index]);
        },
      ),
    );
  }

  Widget ListVidget(InfoModel data) {
    return Container(
      decoration: decoration1(Colors.grey.withOpacity(0.2)),
      padding: EdgeInsets.all(10),
      margin: EdgeInsets.all(5),
      child: ExpandablePanel(
        header: Text(
          data.name,
          style: largeText(Colors.black, bold: true),
        ),
        collapsed: SizedBox.shrink(),
        expanded: Column(
          children: [
            Image.asset(
              data.image,
              fit: BoxFit.fitWidth,
            ),
            Text(
              data.content,
              textAlign: TextAlign.justify,
              softWrap: true,
              style: smallText(
                Colors.black,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class InfoModel {
  String image;
  String name;
  String content;

  InfoModel(this.image, this.name, this.content);
}
